# Generated by Django 2.0.10 on 2019-10-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleor_banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorbanner',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
